### PR TITLE
fix: update moment js to 2.29.2

### PR DESCRIPTION
**Pull request by sanguineti**
Solves #67

### CODE REVIEW

**Comment by sanguineti** [comment]
@vkarpov15 can you pls do a review? cheers

**Comment by sanguineti** [comment]
@vkarpov15 can you pls do a review? cheers

**Comment by sanguineti** [comment]
@vkarpov15 can you pls do a review? cheers

**Comment by sanguineti** [comment]
@vkarpov15 can you pls do a review? cheers

**Comment by lukassr** [comment]
@vkarpov15  are you still supporting this repo?

**Review by vkarpov15 — APPROVED** [review]
Sorry for the delay, LGTM

**Pull request merged**
